### ISSUE TITLE
这个怎么部署哈

### ISSUE THREAD

**Issue by Fsociety-one** [zerosoul/breathe-relaxer#4]
这个项目挺好的哈，怎么部署呢，是只能引用那个网址吗。

**Comment by Fsociety-one** [comment]
写错

**Comment by zerosoul** [comment]
> 这个项目挺好的哈，怎么部署呢，是只能引用那个网址吗。

好久没碰这个项目了，其实就是基于create-react-app构建的一个网站，如果懂前端开发，完全可以自己build出静态文件，然后放到自己服务器。

**Comment by Fsociety-one** [comment]
好吧，虽然还是不会。。。但还是谢了
